Update Syntax Highlighting and Code Font to Vesper Theme
bdsqqq/better-discord-vesper-theme pull request #2
Opened 2024-10-22 14:47 UTC by mohvn

Updating the syntax highlighting of the chats to align with the Vesper theme and changing the code font to JetBrains Mono to achieve visual consistency with Vesper

### Preview:
![image 10](https://github.com/user-attachments/assets/699747bb-8656-4a55-bef8-f0e1e6e43fff)

2024-10-28 18:14 UTC, mohvn commented
![image](https://github.com/user-attachments/assets/63a83d1f-4609-49b9-a311-3c9f8bfd7db1)
Added a border with subtle color to better visualization of code snippet

2025-01-14 17:03 UTC, bdsqqq requested changes
Hey! thank you so much for contributing, can't believe I didn't do codeblocks 😓 

Love the colors, but can you remove the jetbrains mono font? think the font of choice for vesper things would be [Geist](https://vercel.com/font), but don't wanna block the merge of the color improvements on the font change

2025-01-22 12:46 UTC, mohvn commented
Alright, done!

PS: Just used JetBrains Mono 'cause Geist Mono wasn't yet on Google Fonts, but now it works

2025-01-24 18:45 UTC, bdsqqq approved these changes
```

 __       ____    ______            
/\ \     /\  _`\ /\__  _\/'\_/`\    
\ \ \    \ \ \L\_\/_/\ \/\      \   
 \ \ \  __\ \ \L_L  \ \ \ \ \__\ \  
  \ \ \L\ \\ \ \/, \ \ \ \ \ \_/\ \ 
   \ \____/ \ \____/  \ \_\ \_\\ \_\
    \/___/   \/___/    \/_/\/_/ \/_/
                                    
```

2025-01-24 18:45 UTC, merged